/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Cart = Array<CartItem>;
export interface CartItem {
  'color' : string,
  'size' : string,
  'productId' : string,
  'quantity' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface LookbookImage {
  'id' : string,
  'description' : string,
  'image' : ExternalBlob,
  'taggedProducts' : Array<string>,
}
export interface Product {
  'id' : string,
  'isNewProduct' : boolean,
  'name' : string,
  'shortDescriptor' : string,
  'usageCategory' : [] | [UsageCategory],
  'description' : string,
  'productType' : [] | [ProductType],
  'sizes' : Array<string>,
  'isMostLoved' : boolean,
  'isBestseller' : boolean,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export type ProductType = { 'accessory' : null } |
  { 'clothing' : null } |
  { 'other' : string } |
  { 'footwear' : null } |
  { 'electronics' : null };
export interface SiteContent {
  'heroText' : string,
  'footerItems' : Array<string>,
  'sections' : Array<SiteContentBlock>,
  'darkModeEnabled' : boolean,
  'contactDetails' : string,
}
export interface SiteContentBlock {
  'title' : string,
  'content' : string,
  'image' : [] | [ExternalBlob],
}
export type UsageCategory = { 'both' : null } |
  { 'hajj' : null } |
  { 'umrah' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLookbookImage' : ActorMethod<[LookbookImage], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'adminDeleteProduct' : ActorMethod<[string], undefined>,
  'adminUpdateProduct' : ActorMethod<[string, Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'filterProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getAllLookbookImages' : ActorMethod<[], Array<LookbookImage>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBestsellers' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getLookbookImage' : ActorMethod<[string], LookbookImage>,
  'getMostLovedProducts' : ActorMethod<[], Array<Product>>,
  'getNewProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isReady' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSiteContent' : ActorMethod<[string, string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];