/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LookbookImage = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'taggedProducts' : IDL.Vec(IDL.Text),
});
export const UsageCategory = IDL.Variant({
  'both' : IDL.Null,
  'hajj' : IDL.Null,
  'umrah' : IDL.Null,
});
export const ProductType = IDL.Variant({
  'accessory' : IDL.Null,
  'clothing' : IDL.Null,
  'other' : IDL.Text,
  'footwear' : IDL.Null,
  'electronics' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'isNewProduct' : IDL.Bool,
  'name' : IDL.Text,
  'shortDescriptor' : IDL.Text,
  'usageCategory' : IDL.Opt(UsageCategory),
  'description' : IDL.Text,
  'productType' : IDL.Opt(ProductType),
  'sizes' : IDL.Vec(IDL.Text),
  'isMostLoved' : IDL.Bool,
  'isBestseller' : IDL.Bool,
  'category' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const CartItem = IDL.Record({
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BannerImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'link' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const Logo = IDL.Record({
  'link' : IDL.Opt(IDL.Text),
  'image' : ExternalBlob,
  'altText' : IDL.Text,
});
export const SiteContentBlock = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const SiteContent = IDL.Record({
  'heroText' : IDL.Text,
  'footerItems' : IDL.Vec(IDL.Text),
  'companyName' : IDL.Text,
  'sections' : IDL.Vec(SiteContentBlock),
  'darkModeEnabled' : IDL.Bool,
  'contactDetails' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBanner' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Text],
      [],
    ),
  'addLookbookImage' : IDL.Func([LookbookImage], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addToCart' : IDL.Func([IDL.Vec(CartItem)], [], []),
  'adminUpdateProduct' : IDL.Func([IDL.Text, Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeAdminSignupWindow' : IDL.Func([], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteCategory' : IDL.Func([IDL.Text], [IDL.Text], []),
  'filterProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllBanners' : IDL.Func([], [IDL.Vec(BannerImage)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllLookbookImages' : IDL.Func([], [IDL.Vec(LookbookImage)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBestsellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
  'getLookbookImage' : IDL.Func([IDL.Text], [LookbookImage], ['query']),
  'getMostLovedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getNewProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminSignupEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isReady' : IDL.Func([], [IDL.Bool], ['query']),
  'registerAdmin' : IDL.Func([], [IDL.Text], []),
  'removeBanner' : IDL.Func([IDL.Text], [IDL.Text], []),
  'removeFromCart' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBannerOrder' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [IDL.Text],
      [],
    ),
  'updateCategoryDescription' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'updateLogo' : IDL.Func([ExternalBlob, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'updateSiteContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LookbookImage = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'taggedProducts' : IDL.Vec(IDL.Text),
  });
  const UsageCategory = IDL.Variant({
    'both' : IDL.Null,
    'hajj' : IDL.Null,
    'umrah' : IDL.Null,
  });
  const ProductType = IDL.Variant({
    'accessory' : IDL.Null,
    'clothing' : IDL.Null,
    'other' : IDL.Text,
    'footwear' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'isNewProduct' : IDL.Bool,
    'name' : IDL.Text,
    'shortDescriptor' : IDL.Text,
    'usageCategory' : IDL.Opt(UsageCategory),
    'description' : IDL.Text,
    'productType' : IDL.Opt(ProductType),
    'sizes' : IDL.Vec(IDL.Text),
    'isMostLoved' : IDL.Bool,
    'isBestseller' : IDL.Bool,
    'category' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const CartItem = IDL.Record({
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BannerImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'link' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Category = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const Logo = IDL.Record({
    'link' : IDL.Opt(IDL.Text),
    'image' : ExternalBlob,
    'altText' : IDL.Text,
  });
  const SiteContentBlock = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const SiteContent = IDL.Record({
    'heroText' : IDL.Text,
    'footerItems' : IDL.Vec(IDL.Text),
    'companyName' : IDL.Text,
    'sections' : IDL.Vec(SiteContentBlock),
    'darkModeEnabled' : IDL.Bool,
    'contactDetails' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBanner' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'addLookbookImage' : IDL.Func([LookbookImage], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addToCart' : IDL.Func([IDL.Vec(CartItem)], [], []),
    'adminUpdateProduct' : IDL.Func([IDL.Text, Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeAdminSignupWindow' : IDL.Func([], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteCategory' : IDL.Func([IDL.Text], [IDL.Text], []),
    'filterProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllBanners' : IDL.Func([], [IDL.Vec(BannerImage)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllLookbookImages' : IDL.Func([], [IDL.Vec(LookbookImage)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBestsellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
    'getLookbookImage' : IDL.Func([IDL.Text], [LookbookImage], ['query']),
    'getMostLovedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getNewProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminSignupEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isReady' : IDL.Func([], [IDL.Bool], ['query']),
    'registerAdmin' : IDL.Func([], [IDL.Text], []),
    'removeBanner' : IDL.Func([IDL.Text], [IDL.Text], []),
    'removeFromCart' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBannerOrder' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [IDL.Text],
        [],
      ),
    'updateCategoryDescription' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateLogo' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSiteContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };