/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Banner {
  'id' : string,
  'link' : [] | [string],
  'text' : string,
  'image' : ExternalBlob,
}
export type Cart = Array<CartItem>;
export interface CartItem {
  'color' : Color,
  'size' : Size,
  'productId' : ProductId,
  'quantity' : Quantity,
}
export type Category = string;
export type Color = string;
export interface EditableText {
  'lastEdited' : [] | [bigint],
  'content' : string,
  'lastPublished' : [] | [bigint],
  'isDraft' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface LookbookImage {
  'id' : string,
  'description' : string,
  'image' : ExternalBlob,
  'taggedProducts' : Array<ProductId>,
}
export type Price = bigint;
export interface Product {
  'id' : ProductId,
  'isNewProduct' : boolean,
  'name' : string,
  'shortDescriptor' : string,
  'usageCategory' : [] | [UsageCategory],
  'description' : string,
  'productType' : [] | [ProductType],
  'sizes' : Array<Size>,
  'isBestseller' : boolean,
  'category' : Category,
  'badge' : [] | [ProductBadge],
  'colors' : Array<Color>,
  'price' : Price,
  'images' : Array<ExternalBlob>,
}
export type ProductBadge = { 'new' : null } |
  { 'bestseller' : null };
export type ProductId = string;
export type ProductType = { 'accessory' : null } |
  { 'clothing' : null } |
  { 'other' : string } |
  { 'footwear' : null } |
  { 'electronics' : null };
export type Quantity = bigint;
export interface SiteContent {
  'banners' : Array<Banner>,
  'heroText' : EditableText,
  'footerItems' : Array<string>,
  'sections' : Array<SiteContentBlock>,
  'previewMode' : boolean,
  'darkModeEnabled' : boolean,
  'contactDetails' : EditableText,
}
export interface SiteContentBlock {
  'title' : string,
  'content' : string,
  'image' : [] | [ExternalBlob],
}
export type Size = string;
export type UsageCategory = { 'both' : null } |
  { 'hajj' : null } |
  { 'umrah' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBanner' : ActorMethod<[ExternalBlob, string, [] | [string]], Banner>,
  'addLookbookImage' : ActorMethod<[LookbookImage], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'adminDeleteProduct' : ActorMethod<[ProductId], undefined>,
  'adminUpdateProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Authenticate admin using email and password.
   */
  'authenticateAdminWithEmailPassword' : ActorMethod<
    [string, string],
    undefined
  >,
  'deleteBanner' : ActorMethod<[string], undefined>,
  'filterProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'filterProductsByColor' : ActorMethod<[Color], Array<Product>>,
  'filterProductsBySize' : ActorMethod<[Size], Array<Product>>,
  'getAllLookbookImages' : ActorMethod<[], Array<LookbookImage>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBanners' : ActorMethod<[], Array<Banner>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getLookbookImage' : ActorMethod<[string], LookbookImage>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishSiteContent' : ActorMethod<[], undefined>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDraft' : ActorMethod<[string, boolean], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'toggleDarkMode' : ActorMethod<[boolean], undefined>,
  'unlockBootstrapAdminPrivileges' : ActorMethod<[string, string], undefined>,
  'updateBanner' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [string], [] | [string]],
    Banner
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];