/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Banner = IDL.Record({
  'id' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'text' : IDL.Text,
  'image' : ExternalBlob,
});
export const ProductId = IDL.Text;
export const LookbookImage = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'taggedProducts' : IDL.Vec(ProductId),
});
export const Size = IDL.Text;
export const Category = IDL.Text;
export const Color = IDL.Text;
export const Price = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(Size),
  'category' : Category,
  'colors' : IDL.Vec(Color),
  'price' : Price,
  'images' : IDL.Vec(ExternalBlob),
});
export const Quantity = IDL.Nat;
export const CartItem = IDL.Record({
  'color' : Color,
  'size' : Size,
  'productId' : ProductId,
  'quantity' : Quantity,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Cart = IDL.Vec(CartItem);
export const EditableText = IDL.Record({
  'lastEdited' : IDL.Opt(IDL.Int),
  'content' : IDL.Text,
  'lastPublished' : IDL.Opt(IDL.Int),
  'isDraft' : IDL.Bool,
});
export const SiteContentBlock = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const SiteContent = IDL.Record({
  'banners' : IDL.Vec(Banner),
  'heroText' : EditableText,
  'footerItems' : IDL.Vec(IDL.Text),
  'sections' : IDL.Vec(SiteContentBlock),
  'previewMode' : IDL.Bool,
  'darkModeEnabled' : IDL.Bool,
  'contactDetails' : EditableText,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBanner' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Opt(IDL.Text)],
      [Banner],
      [],
    ),
  'addLookbookImage' : IDL.Func([LookbookImage], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addToCart' : IDL.Func([CartItem], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'adminDeleteProduct' : IDL.Func([ProductId], [], []),
  'adminUpdateProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBanner' : IDL.Func([IDL.Text], [], []),
  'filterProductsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'filterProductsByColor' : IDL.Func([Color], [IDL.Vec(Product)], ['query']),
  'filterProductsBySize' : IDL.Func([Size], [IDL.Vec(Product)], ['query']),
  'getAllLookbookImages' : IDL.Func([], [IDL.Vec(LookbookImage)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getLookbookImage' : IDL.Func([IDL.Text], [LookbookImage], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishSiteContent' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDraft' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'toggleDarkMode' : IDL.Func([IDL.Bool], [], []),
  'updateBanner' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Banner],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Banner = IDL.Record({
    'id' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
    'image' : ExternalBlob,
  });
  const ProductId = IDL.Text;
  const LookbookImage = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'taggedProducts' : IDL.Vec(ProductId),
  });
  const Size = IDL.Text;
  const Category = IDL.Text;
  const Color = IDL.Text;
  const Price = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(Size),
    'category' : Category,
    'colors' : IDL.Vec(Color),
    'price' : Price,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Quantity = IDL.Nat;
  const CartItem = IDL.Record({
    'color' : Color,
    'size' : Size,
    'productId' : ProductId,
    'quantity' : Quantity,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Cart = IDL.Vec(CartItem);
  const EditableText = IDL.Record({
    'lastEdited' : IDL.Opt(IDL.Int),
    'content' : IDL.Text,
    'lastPublished' : IDL.Opt(IDL.Int),
    'isDraft' : IDL.Bool,
  });
  const SiteContentBlock = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const SiteContent = IDL.Record({
    'banners' : IDL.Vec(Banner),
    'heroText' : EditableText,
    'footerItems' : IDL.Vec(IDL.Text),
    'sections' : IDL.Vec(SiteContentBlock),
    'previewMode' : IDL.Bool,
    'darkModeEnabled' : IDL.Bool,
    'contactDetails' : EditableText,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBanner' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Opt(IDL.Text)],
        [Banner],
        [],
      ),
    'addLookbookImage' : IDL.Func([LookbookImage], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addToCart' : IDL.Func([CartItem], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'adminDeleteProduct' : IDL.Func([ProductId], [], []),
    'adminUpdateProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBanner' : IDL.Func([IDL.Text], [], []),
    'filterProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'filterProductsByColor' : IDL.Func([Color], [IDL.Vec(Product)], ['query']),
    'filterProductsBySize' : IDL.Func([Size], [IDL.Vec(Product)], ['query']),
    'getAllLookbookImages' : IDL.Func([], [IDL.Vec(LookbookImage)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getLookbookImage' : IDL.Func([IDL.Text], [LookbookImage], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishSiteContent' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDraft' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'toggleDarkMode' : IDL.Func([IDL.Bool], [], []),
    'updateBanner' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Banner],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };