/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type ProductType = {
    __kind__: "accessory";
    accessory: null;
} | {
    __kind__: "clothing";
    clothing: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "footwear";
    footwear: null;
} | {
    __kind__: "electronics";
    electronics: null;
};
export interface SiteContentBlock {
    title: string;
    content: string;
    image?: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LookbookImage {
    id: string;
    description: string;
    image: ExternalBlob;
    taggedProducts: Array<string>;
}
export type Cart = Array<CartItem>;
export interface CartItem {
    color: string;
    size: string;
    productId: string;
    quantity: bigint;
}
export interface SiteContent {
    heroText: string;
    footerItems: Array<string>;
    sections: Array<SiteContentBlock>;
    darkModeEnabled: boolean;
    contactDetails: string;
}
export interface Product {
    id: string;
    isNewProduct: boolean;
    name: string;
    shortDescriptor: string;
    usageCategory?: UsageCategory;
    description: string;
    productType?: ProductType;
    sizes: Array<string>;
    isMostLoved: boolean;
    isBestseller: boolean;
    category: string;
    colors: Array<string>;
    price: bigint;
    images: Array<ExternalBlob>;
}
export interface UserProfile {
    name: string;
}
export enum UsageCategory {
    both = "both",
    hajj = "hajj",
    umrah = "umrah"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLookbookImage(image: LookbookImage): Promise<void>;
    addProduct(product: Product): Promise<void>;
    addToCart(item: CartItem): Promise<void>;
    adminDeleteProduct(productId: string): Promise<void>;
    adminUpdateProduct(productId: string, product: Product): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    filterProductsByCategory(category: string): Promise<Array<Product>>;
    getAllLookbookImages(): Promise<Array<LookbookImage>>;
    getAllProducts(): Promise<Array<Product>>;
    getBestsellers(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Cart>;
    getLookbookImage(imageId: string): Promise<LookbookImage>;
    getMostLovedProducts(): Promise<Array<Product>>;
    getNewProducts(): Promise<Array<Product>>;
    getProduct(productId: string): Promise<Product>;
    getSiteContent(): Promise<SiteContent>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isReady(): Promise<boolean>;
    removeFromCart(productId: string, size: string, color: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateSiteContent(heroText: string, contactDetails: string, darkModeEnabled: boolean): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, LookbookImage as _LookbookImage, Product as _Product, ProductType as _ProductType, SiteContent as _SiteContent, SiteContentBlock as _SiteContentBlock, UsageCategory as _UsageCategory, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLookbookImage(arg0: LookbookImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLookbookImage(await to_candid_LookbookImage_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLookbookImage(await to_candid_LookbookImage_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addToCart(arg0: CartItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0);
            return result;
        }
    }
    async adminDeleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProduct(arg0);
            return result;
        }
    }
    async adminUpdateProduct(arg0: string, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProduct(arg0, await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProduct(arg0, await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async filterProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProductsByCategory(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProductsByCategory(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLookbookImages(): Promise<Array<LookbookImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLookbookImages();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLookbookImages();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBestsellers(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestsellers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestsellers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getLookbookImage(arg0: string): Promise<LookbookImage> {
        if (this.processError) {
            try {
                const result = await this.actor.getLookbookImage(arg0);
                return from_candid_LookbookImage_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLookbookImage(arg0);
            return from_candid_LookbookImage_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMostLovedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostLovedProducts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostLovedProducts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewProducts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewProducts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteContent(): Promise<SiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteContent();
                return from_candid_SiteContent_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteContent();
            return from_candid_SiteContent_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isReady(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isReady();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isReady();
            return result;
        }
    }
    async removeFromCart(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateSiteContent(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteContent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteContent(arg0, arg1, arg2);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_LookbookImage_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LookbookImage): Promise<LookbookImage> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ProductType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_SiteContentBlock_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteContentBlock): Promise<SiteContentBlock> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_SiteContent_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteContent): Promise<SiteContent> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UsageCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UsageCategory): UsageCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UsageCategory]): UsageCategory | null {
    return value.length === 0 ? null : from_candid_UsageCategory_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductType]): ProductType | null {
    return value.length === 0 ? null : from_candid_ProductType_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isNewProduct: boolean;
    name: string;
    shortDescriptor: string;
    usageCategory: [] | [_UsageCategory];
    description: string;
    productType: [] | [_ProductType];
    sizes: Array<string>;
    isMostLoved: boolean;
    isBestseller: boolean;
    category: string;
    colors: Array<string>;
    price: bigint;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    isNewProduct: boolean;
    name: string;
    shortDescriptor: string;
    usageCategory?: UsageCategory;
    description: string;
    productType?: ProductType;
    sizes: Array<string>;
    isMostLoved: boolean;
    isBestseller: boolean;
    category: string;
    colors: Array<string>;
    price: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        isNewProduct: value.isNewProduct,
        name: value.name,
        shortDescriptor: value.shortDescriptor,
        usageCategory: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.usageCategory)),
        description: value.description,
        productType: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.productType)),
        sizes: value.sizes,
        isMostLoved: value.isMostLoved,
        isBestseller: value.isBestseller,
        category: value.category,
        colors: value.colors,
        price: value.price,
        images: await from_candid_vec_n29(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    image: _ExternalBlob;
    taggedProducts: Array<string>;
}): Promise<{
    id: string;
    description: string;
    image: ExternalBlob;
    taggedProducts: Array<string>;
}> {
    return {
        id: value.id,
        description: value.description,
        image: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.image),
        taggedProducts: value.taggedProducts
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heroText: string;
    footerItems: Array<string>;
    sections: Array<_SiteContentBlock>;
    darkModeEnabled: boolean;
    contactDetails: string;
}): Promise<{
    heroText: string;
    footerItems: Array<string>;
    sections: Array<SiteContentBlock>;
    darkModeEnabled: boolean;
    contactDetails: string;
}> {
    return {
        heroText: value.heroText,
        footerItems: value.footerItems,
        sections: await from_candid_vec_n39(_uploadFile, _downloadFile, value.sections),
        darkModeEnabled: value.darkModeEnabled,
        contactDetails: value.contactDetails
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    image: [] | [_ExternalBlob];
}): Promise<{
    title: string;
    content: string;
    image?: ExternalBlob;
}> {
    return {
        title: value.title,
        content: value.content,
        image: record_opt_to_undefined(await from_candid_opt_n42(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    hajj: null;
} | {
    umrah: null;
}): UsageCategory {
    return "both" in value ? UsageCategory.both : "hajj" in value ? UsageCategory.hajj : "umrah" in value ? UsageCategory.umrah : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accessory: null;
} | {
    clothing: null;
} | {
    other: string;
} | {
    footwear: null;
} | {
    electronics: null;
}): {
    __kind__: "accessory";
    accessory: null;
} | {
    __kind__: "clothing";
    clothing: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "footwear";
    footwear: null;
} | {
    __kind__: "electronics";
    electronics: null;
} {
    return "accessory" in value ? {
        __kind__: "accessory",
        accessory: value.accessory
    } : "clothing" in value ? {
        __kind__: "clothing",
        clothing: value.clothing
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "footwear" in value ? {
        __kind__: "footwear",
        footwear: value.footwear
    } : "electronics" in value ? {
        __kind__: "electronics",
        electronics: value.electronics
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LookbookImage>): Promise<Array<LookbookImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LookbookImage_n32(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SiteContentBlock>): Promise<Array<SiteContentBlock>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SiteContentBlock_n40(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_LookbookImage_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LookbookImage): Promise<_LookbookImage> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ProductType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UsageCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UsageCategory): _UsageCategory {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isNewProduct: boolean;
    name: string;
    shortDescriptor: string;
    usageCategory?: UsageCategory;
    description: string;
    productType?: ProductType;
    sizes: Array<string>;
    isMostLoved: boolean;
    isBestseller: boolean;
    category: string;
    colors: Array<string>;
    price: bigint;
    images: Array<ExternalBlob>;
}): Promise<{
    id: string;
    isNewProduct: boolean;
    name: string;
    shortDescriptor: string;
    usageCategory: [] | [_UsageCategory];
    description: string;
    productType: [] | [_ProductType];
    sizes: Array<string>;
    isMostLoved: boolean;
    isBestseller: boolean;
    category: string;
    colors: Array<string>;
    price: bigint;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        isNewProduct: value.isNewProduct,
        name: value.name,
        shortDescriptor: value.shortDescriptor,
        usageCategory: value.usageCategory ? candid_some(to_candid_UsageCategory_n13(_uploadFile, _downloadFile, value.usageCategory)) : candid_none(),
        description: value.description,
        productType: value.productType ? candid_some(to_candid_ProductType_n15(_uploadFile, _downloadFile, value.productType)) : candid_none(),
        sizes: value.sizes,
        isMostLoved: value.isMostLoved,
        isBestseller: value.isBestseller,
        category: value.category,
        colors: value.colors,
        price: value.price,
        images: await to_candid_vec_n17(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    image: ExternalBlob;
    taggedProducts: Array<string>;
}): Promise<{
    id: string;
    description: string;
    image: _ExternalBlob;
    taggedProducts: Array<string>;
}> {
    return {
        id: value.id,
        description: value.description,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        taggedProducts: value.taggedProducts
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UsageCategory): {
    both: null;
} | {
    hajj: null;
} | {
    umrah: null;
} {
    return value == UsageCategory.both ? {
        both: null
    } : value == UsageCategory.hajj ? {
        hajj: null
    } : value == UsageCategory.umrah ? {
        umrah: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "accessory";
    accessory: null;
} | {
    __kind__: "clothing";
    clothing: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "footwear";
    footwear: null;
} | {
    __kind__: "electronics";
    electronics: null;
}): {
    accessory: null;
} | {
    clothing: null;
} | {
    other: string;
} | {
    footwear: null;
} | {
    electronics: null;
} {
    return value.__kind__ === "accessory" ? {
        accessory: value.accessory
    } : value.__kind__ === "clothing" ? {
        clothing: value.clothing
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "footwear" ? {
        footwear: value.footwear
    } : value.__kind__ === "electronics" ? {
        electronics: value.electronics
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
